/**
 * The pure half of the Text Trigger Editor: the text the dialog shows, and the words
 * around it. Nothing here touches the editor, so it has the tests.
 */
import type { TriggerRecord } from "@scm-js/plugin-api";

/** A run of the trigger list another plugin generates and owns (`api.triggers.claims`). */
export interface ClaimedRun {
  label: string;
  start: number;
  count: number;
}

/** The comment that opens a fenced run. */
export function fenceOpen(label: string, count: number): string {
  return `//== Generated by ${label}: ${count} trigger${count === 1 ? "" : "s"}. Edit them there instead — changes here take them out of its hands. ==//`;
}

/** The comment that closes one. */
export const FENCE_CLOSE = "//== End of the generated run ==//";

/**
 * The list as text, with every claimed run fenced in comments so a reader knows which
 * triggers a rebuild will replace. The fences are comments to the parser, so the text
 * compiles back to the same list, generated triggers and all — they merely stop being
 * the plugin's once they are edited here. Overlapping claims: the first wins.
 */
export function fencedText(list: TriggerRecord[], runs: ClaimedRun[], print: (slice: TriggerRecord[]) => string): string {
  const real = runs.filter((r) => r.count > 0).sort((a, b) => a.start - b.start);
  if (real.length === 0) return print(list);
  const parts: string[] = [];
  let at = 0;
  for (const { label, start, count } of real) {
    if (start < at) continue;
    parts.push(print(list.slice(at, start)));
    parts.push(`${fenceOpen(label, count)}\n\n`);
    parts.push(print(list.slice(start, start + count)));
    parts.push(`${FENCE_CLOSE}\n`);
    at = start + count;
  }
  parts.push(print(list.slice(at)));
  return parts.filter((p) => p !== "").join("\n");
}

/** A parse error as the dialog shows it: the line (when the parser said) and the message. */
export interface TextError {
  line: number | null;
  message: string;
}

/** The editor's `TriggerTextError` carries the line; anything else is shown as it is. */
export function describeError(err: unknown): TextError {
  if (err instanceof Error) {
    const line = (err as { line?: unknown }).line;
    return { line: typeof line === "number" && Number.isFinite(line) ? line : null, message: err.message };
  }
  return { line: null, message: String(err) };
}

export function countLines(text: string): number {
  let n = 1;
  for (let i = 0; i < text.length; i++) if (text.charCodeAt(i) === 10) n++;
  return n;
}

/** The gutter: one number per line, the failing line marked. */
export function gutterText(lines: number, errorLine: number | null): string {
  const out: string[] = [];
  for (let i = 1; i <= lines; i++) out.push(i === errorLine ? `▶${i}` : String(i));
  return out.join("\n");
}

/** The line under the editor: a count, the syntax, which list, and what just happened. */
export function statusText(lines: number, briefing: boolean, status: string): string {
  return `${lines} line${lines === 1 ? "" : "s"} · TrigEdit syntax · ${briefing ? "mission briefing (MBRF)" : "triggers (TRIG)"}${status ? ` · ${status}` : ""}`;
}

/** "Compiled 3 triggers." / "Compiled 1 briefing." */
export function compiledText(count: number, briefing: boolean): string {
  const what = briefing ? "briefing" : "trigger";
  return `Compiled ${count} ${what}${count === 1 ? "" : "s"}.`;
}
