import { describe, expect, it } from "vitest";
import type { TriggerRecord } from "@scm-js/plugin-api";
import { compiledText, countLines, describeError, FENCE_CLOSE, fencedText, fenceOpen, gutterText, statusText } from "../text";

// The printer under test only needs to tell the records apart.
const rec = (n: number) => ({ n }) as unknown as TriggerRecord;
const list = [rec(0), rec(1), rec(2), rec(3), rec(4)];
const print = (slice: TriggerRecord[]) => slice.map((t) => `T${(t as unknown as { n: number }).n}`).join("\n") + (slice.length ? "\n" : "");

describe("fencing", () => {
  it("prints the list as it is when nothing is claimed", () => {
    expect(fencedText(list, [], print)).toBe("T0\nT1\nT2\nT3\nT4\n");
    expect(fencedText(list, [{ label: "x", start: 1, count: 0 }], print)).toBe("T0\nT1\nT2\nT3\nT4\n");
  });

  it("fences a claimed run in comments, the text around it untouched", () => {
    const text = fencedText(list, [{ label: "the trigger script", start: 1, count: 2 }], print);
    expect(text).toBe(["T0\n", `${fenceOpen("the trigger script", 2)}\n\n`, "T1\nT2\n", `${FENCE_CLOSE}\n`, "T3\nT4\n"].join("\n"));
    expect(text).toContain("//== Generated by the trigger script: 2 triggers. Edit them there instead");
  });

  it("fences several runs in order and lets the first of two overlapping claims win", () => {
    const text = fencedText(list, [{ label: "b", start: 3, count: 1 }, { label: "a", start: 0, count: 2 }, { label: "c", start: 1, count: 3 }], print);
    const fences = text.split("\n").filter((l) => l.startsWith("//=="));
    expect(fences).toEqual([fenceOpen("a", 2), FENCE_CLOSE, fenceOpen("b", 1), FENCE_CLOSE]);
    expect(text.indexOf("T2")).toBeGreaterThan(text.indexOf(FENCE_CLOSE));
  });

  it("says one trigger in the singular", () => {
    expect(fenceOpen("x", 1)).toMatch(/: 1 trigger\. /);
  });
});

describe("words", () => {
  it("reads the line off the editor's parse error and shows anything else as it is", () => {
    const err = Object.assign(new Error("Line 4: expected )"), { line: 4 });
    expect(describeError(err)).toEqual({ line: 4, message: "Line 4: expected )" });
    expect(describeError(new Error("No map is open."))).toEqual({ line: null, message: "No map is open." });
    expect(describeError("boom")).toEqual({ line: null, message: "boom" });
  });

  it("counts lines and marks the failing one in the gutter", () => {
    expect(countLines("")).toBe(1);
    expect(countLines("a\nb\n")).toBe(3);
    expect(gutterText(3, null)).toBe("1\n2\n3");
    expect(gutterText(3, 2)).toBe("1\n▶2\n3");
  });

  it("writes the status line", () => {
    expect(statusText(1, false, "")).toBe("1 line · TrigEdit syntax · triggers (TRIG)");
    expect(statusText(12, true, "Formatted.")).toBe("12 lines · TrigEdit syntax · mission briefing (MBRF) · Formatted.");
    expect(compiledText(1, false)).toBe("Compiled 1 trigger.");
    expect(compiledText(3, true)).toBe("Compiled 3 briefings.");
  });
});
